import { Appointment, Notification, User } from "../domain/entities";
import { AppointmentRepository, NotificationRepository, UserRepository } from "../domain/repositories";
import { PriorityStrategyFactory } from "../domain/priority-strategy";
import { AcceptAppointmentDTO, CreateAppointmentDTO, LoginDTO, RegisterUserDTO, UpdateAppointmentStatusDTO } from "./dtos";
const createId = () => typeof crypto !== "undefined" && crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2);
export class RegisterUserUseCase { constructor(private readonly users: UserRepository) {} execute(dto: RegisterUserDTO): User { const existingUser = this.users.findByEmail(dto.email); if (existingUser) throw new Error("E-mail já cadastrado."); const user: User = { id: createId(), name: dto.name, email: dto.email.toLowerCase(), password: dto.password, role: dto.role, specialty: dto.specialty, createdAt: new Date().toISOString() }; return this.users.save(user); } }
export class LoginUseCase { constructor(private readonly users: UserRepository) {} execute(dto: LoginDTO): User { const user = this.users.findByEmail(dto.email.toLowerCase()); if (!user || user.password !== dto.password) throw new Error("Credenciais inválidas."); return user; } }
export class CreateAppointmentUseCase { constructor(private readonly appointments: AppointmentRepository, private readonly notifications: NotificationRepository) {} execute(dto: CreateAppointmentDTO): Appointment { const priorityScore = PriorityStrategyFactory.create(dto.urgency).calculate(); const appointment: Appointment = { id: createId(), clientId: dto.clientId, clientName: dto.clientName, serviceType: dto.serviceType, description: dto.description, urgency: dto.urgency, priorityScore, status: "PENDING", scheduledDate: dto.scheduledDate, createdAt: new Date().toISOString() }; const savedAppointment = this.appointments.save(appointment); this.notifications.save({ id: createId(), userId: dto.clientId, title: "Solicitação registrada", message: `Sua solicitação de ${dto.serviceType} foi enviada para prestadores disponíveis.`, createdAt: new Date().toISOString() }); return savedAppointment; } }
export class AcceptAppointmentUseCase { constructor(private readonly appointments: AppointmentRepository, private readonly notifications: NotificationRepository) {} execute(dto: AcceptAppointmentDTO): Appointment { const appointment = this.appointments.findById(dto.appointmentId); if (!appointment) throw new Error("Solicitação não encontrada."); if (appointment.status !== "PENDING") throw new Error("Essa solicitação não está mais disponível."); const updatedAppointment: Appointment = { ...appointment, providerId: dto.providerId, providerName: dto.providerName, status: "ACCEPTED" }; const savedAppointment = this.appointments.update(updatedAppointment); this.notifications.save({ id: createId(), userId: appointment.clientId, title: "Prestador vinculado", message: `${dto.providerName} aceitou seu atendimento.`, createdAt: new Date().toISOString() }); return savedAppointment; } }
export class UpdateAppointmentStatusUseCase { constructor(private readonly appointments: AppointmentRepository) {} execute(dto: UpdateAppointmentStatusDTO): Appointment { const appointment = this.appointments.findById(dto.appointmentId); if (!appointment) throw new Error("Solicitação não encontrada."); const updatedAppointment: Appointment = { ...appointment, status: dto.status }; return this.appointments.update(updatedAppointment); } }
